development:
  adapter: mysql
  database: facebook_development
  username: root
  password: 
  host: localhost

test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000

production:
  adapter: mysql
  database: facebook
  username: root
  password: 
  host: localhost
