development:
  adapter: mysql
  database: facebook_development
  username: root
  password: 
  host: localhost

production:
  adapter: mysql
  database: facebook
  username: root
  password: 
  host: localhost
