dev_old:
  adapter: mysql
  database: faces_dev
  username: root
  password: 
  host: localhost

development:
  adapter: postgresql
  database: faces_dev
  username: postgres
  password:
  host: localhost

test:
  adapter: mysql
  database: facebook_test
  username: root
  password: 
  host: localhost

production:
  adapter: mysql
  database: facebook
  username: root
  password: 
  host: localhost
